server:
    port: 8883
spring:
    application:
        name: sleuth-zipkin-server
    cloud:
        nacos:
            discovery:
                server-addr: localhost:8848
                username: nacos
                password: nacos
    zipkin:
        base-url: http://127.0.0.1:9411/
    sleuth:
        sampler:
            probability: 1.0
        web:
            enabled: true